CREATE TABLE `Spills` (
  `IncidentNumber` INTEGER PRIMARY KEY,
  `IncidentType` TEXT DEFAULT NULL,
  `Latitude` REAL DEFAULT NULL,
  `Longitude` REAL DEFAULT NULL,
  `Location` TEXT DEFAULT NULL,
  `IncidentLSD` INTEGER DEFAULT NULL,
  `IncidentSection` INTEGER DEFAULT NULL,
  `IncidentTownship` INTEGER DEFAULT NULL,
  `IncidentRange` INTEGER DEFAULT NULL,
  `IncidentMeridian` INTEGER DEFAULT NULL,
  `LicenceNumber` TEXT DEFAULT NULL,
  `LicenceType` TEXT DEFAULT NULL,
  `IncidentDate` TEXT DEFAULT NULL,
  `IncidentNotificationDate` TEXT DEFAULT NULL,
  `IncidentCompleteDate` TEXT DEFAULT NULL,
  `Source` TEXT DEFAULT NULL,
  `CauseCategory` TEXT DEFAULT NULL,
  `CauseType` TEXT DEFAULT NULL,
  `FailureType` TEXT DEFAULT NULL,
  `StrikeArea` TEXT DEFAULT NULL,
  `FieldCentre` TEXT DEFAULT NULL,
  `LicenseeID` INTEGER(4) DEFAULT NULL,
  `LicenseeName` TEXT DEFAULT NULL,
  `InjuryCount` INTEGER DEFAULT NULL,
  `FatalityCount` INTEGER DEFAULT NULL,
  `Jurisdiction` TEXT DEFAULT NULL,
  `ReleaseOffsite` TEXT DEFAULT NULL,
  `SensitiveArea` TEXT DEFAULT NULL,
  `PublicAffected` TEXT DEFAULT NULL,
  `EnvironmentAffected` TEXT DEFAULT NULL,
  `WildlifeLivestockAffected` TEXT DEFAULT NULL,
  `AreaAffected` TEXT DEFAULT NULL,
  `PublicEvacuatedCount` INTEGER DEFAULT NULL,
  `ReleaseCleanupDate` TEXT DEFAULT NULL,
  `PipelineLicenceSegmentID` INTEGER DEFAULT NULL,
  `PipelineLicenceLineNo` INTEGER DEFAULT NULL,
  `PipeDamageType` TEXT DEFAULT NULL,
  `PipeTestFailure` TEXT DEFAULT NULL,
  `PipelineOutsideDiameter(mm)` REAL DEFAULT NULL,
  `PipeGrade` TEXT DEFAULT NULL,
  `PipeWallThickness(mm)` REAL DEFAULT NULL,
  `Substance Released` TEXT DEFAULT NULL,
  `Volume Released` REAL DEFAULT NULL,
  `Volume Recovered` REAL DEFAULT NULL,
  `Substance Released 2` TEXT DEFAULT NULL,
  `Volume Released 2` REAL DEFAULT NULL,
  `Volume Recovered 2` REAL DEFAULT NULL,
  `Substance Released 3` TEXT DEFAULT NULL,
  `Volume Released 3` REAL DEFAULT NULL,
  `Volume Recovered 3` REAL DEFAULT NULL,
  `Substance Released 4` TEXT DEFAULT NULL,
  `Volume Released 4` REAL DEFAULT NULL,
  `Volume Recovered 4` REAL DEFAULT NULL
);

CREATE INDEX spills_idx ON `Spills` (`Location`, `Latitude`, `Longitude`, 
  `IncidentDate`, `FailureType`, `LicenseeName`, `Source`, `InjuryCount`,
  `FatalityCount`, `Substance Released`, `Volume Released`);

.mode csv
.separator "|"
.import Spills.csv Spills